Feat/integrate
DecentralizationFloks/p-ride pull request #8
Opened 2022-01-19 15:06 UTC by iBharath01

connect auth pages to backend

2022-01-19 16:15 UTC, pavankpdev requested changes

2022-01-19 16:15 UTC, pavankpdev commented on client/pages/auth/forgot.js
> +      console.log(forgotHandler);
Remove log

2022-01-19 16:15 UTC, pavankpdev commented on client/pages/auth/forgot.js
> +      localStorage.setItem(
Do not store forgot password token in localstorage

2022-01-19 16:15 UTC, pavankpdev commented on client/.env
> +NEXT_PUBLIC_NODE_API_URL=http://api.peerride.tech
Remove ENV

2022-01-19 16:15 UTC, pavankpdev commented on client/pages/auth/login.js
> +      console.log(loginHandler);
Remove logs

2022-01-19 16:15 UTC, pavankpdev commented on client/pages/auth/login.js
> +      );
Redirect to dashbord

2022-01-19 16:15 UTC, pavankpdev commented on client/pages/auth/register.js
>  const Login = () => {
update function name

2022-01-19 16:15 UTC, pavankpdev commented on client/pages/auth/register.js
> +      console.log(registerHandler);
Remove Logs

2022-01-19 16:15 UTC, pavankpdev commented on client/pages/auth/register.js
> +      );
Add redirect to dashboard

2022-01-22 13:47 UTC, pavan38kp requested changes

2022-01-22 13:47 UTC, pavan38kp commented on client/pages/auth/register.js
> +const register = () => {
Capitalize function name

2022-01-22 13:51 UTC, pavankpdev approved these changes

2022-01-22 13:51 UTC, merged